Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(semicircle_slow.py:4098693): Gdk-CRITICAL **: 17:54:32.319: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
2023-09-27 17:54:35.258355: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2023-09-27 17:54:35.258521: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-09-27 17:54:35.365778: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "semicircle_slow.py", line 154, in <module>
    main()
  File "semicircle_slow.py", line 145, in main
    mb.train_features(feature_extractor, shuffled_train_x, shuffled_train_y, shuffled_val_x, shuffled_val_y,
  File "/home1/jmoukpe2016/keras-functional-api/models/modeling.py", line 370, in train_features
    model.fit(X_combined, y_combined, epochs=best_epoch, batch_size=batch_size,
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
    return fn(*args, **kwargs)
TypeError: fit() got an unexpected keyword argument 'clallbacks'
srun: error: gpu01: task 0: Exited with exit code 1
